create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  name text not null,
  message text not null,
  photo_url text,
  created_at timestamptz not null default now()
);

alter table public.comments enable row level security;

drop policy if exists "Comments are readable by everyone" on public.comments;
create policy "Comments are readable by everyone"
on public.comments for select
using (true);

drop policy if exists "Anyone can post comments" on public.comments;
create policy "Anyone can post comments"
on public.comments for insert
with check (
  length(trim(name)) between 1 and 80
  and length(trim(message)) between 1 and 1000
);

create index if not exists comments_created_at_idx
on public.comments (created_at desc);
